require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"
    - "spec/support/test_factories.rb"
    - "app/components/**/*"

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'app/admin/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**.rb'
    - "app/components/**/*"

Metrics/ParameterLists:
  Exclude:
    - "app/components/**/*"

Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/seeds.rb'
    - 'app/components/**/*'
   
Naming/RescuedExceptionsVariableName:
  PreferredName: 'exception'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

RSpec:
  Exclude:
    - 'spec/factories/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Exclude:
    - 'spec/requests/**/*'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/requests/**/*"

RSpec/NestedGroups:
  Max: 4

AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'docker/**/*'
    - 'doc/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
