# test_runner.yml
adapters:
  rspec_with_spring:
    adapter: custom
    file_pattern: ".*_spec.rb"
    command: "./bin/rspec"
    commands:
      all: "{command}"
      file: "{command} {file}"
      line: "{command} {file}:{line}"
