---
development:
  cloud_name: "congregation-cloud-name"
  api_key: <%= ENV['CLOUDINARY_API_KEY'] || 'dummy-key' %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] || 'dummy-secret' %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: "congregation-cloud-name"
  api_key: <%= ENV['CLOUDINARY_API_KEY'] || 'dummy-key' %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] || 'dummy-secret' %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: "congregation-cloud-name"
  api_key: <%= ENV['CLOUDINARY_API_KEY'] || 'dummy-key' %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] || 'dummy-secret' %>
  enhance_image_tag: true
  static_file_support: false
