service: khtools
image: mjacobus/khtools

servers:
  web:
    - deploy@vps58187.publiccloud.com.br

env:
  clear:
    RAILS_ENV: production
    PORT: 3001

registry:
  username: ~
  password: ~

volumes:
  - /home/deploy/_databases/khtools:/databases
