name: Rails Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Set up and run tests
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create db:migrate
          bundle exec rspec

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
